// Edge function called directly by device firmware to complete a pairing flow.
// The device submits the pairing token (from the bundle generated by
// create-device-pairing) along with its serial number. The function validates
// the token, creates a device record and its default sensor config, then marks
// the token as used — all inside a single transaction. Re-registration of an
// existing device by the same owner is allowed (e.g. after a factory reset);
// registration of a serial number already owned by a different user is rejected
// and recorded on the token so the web app wizard can surface a clear error.

import { Pool } from "https://deno.land/x/postgres@v0.19.3/mod.ts";
import type { PoolClient } from "https://deno.land/x/postgres@v0.19.3/mod.ts";

const DEFAULT_HUMIDITY_CONFIG = {
  minHumidityThreshold: 15,
  airValue: 520,
  waterValue: 260,
  sleepDurationSeconds: 3600,
};

interface RegisterDeviceRequest {
  token?: string;
  serialNumber?: string;
}

class RegisterDeviceError extends Error {
  status: number;

  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

async function registerDevice(
  client: PoolClient,
  token: string,
  serialNumber: string,
): Promise<{ deviceId: number; serialNumber: string }> {
  await client.queryObject("BEGIN");

  try {
    const tokenResult = await client.queryObject<{
      id: string;
      user_id: string;
      plant_id: number | null;
      expires_at: Date;
      used_at: Date | null;
    }>`
      SELECT id, user_id, plant_id, expires_at, used_at
      FROM public.device_pairing_tokens
      WHERE token = ${token}
      FOR UPDATE
    `;

    const pairing = tokenResult.rows[0];
    if (!pairing) {
      throw new RegisterDeviceError(400, "Invalid pairing token");
    }
    if (pairing.used_at) {
      throw new RegisterDeviceError(400, "Pairing token already used");
    }
    if (pairing.expires_at.getTime() <= Date.now()) {
      throw new RegisterDeviceError(400, "Pairing token expired");
    }

    // Check for an existing device with this serial number.
    const existingResult = await client.queryObject<{
      id: number;
      user_id: string;
    }>`
      SELECT id, user_id FROM public.devices WHERE "serialNumber" = ${serialNumber}
    `;

    if (existingResult.rows.length > 0) {
      const existingDevice = existingResult.rows[0];

      if (existingDevice.user_id === pairing.user_id) {
        // Same owner: treat as a re-registration (e.g. after factory reset to
        // update WiFi credentials). Mark the token as used against the existing
        // device and return success so the firmware can proceed normally.
        await client.queryObject`
          UPDATE public.device_pairing_tokens
          SET
            used_at = now(),
            registered_serial_number = ${serialNumber},
            registered_device_id = ${existingDevice.id}
          WHERE id = ${pairing.id}
        `;

        await client.queryObject("COMMIT");
        return { deviceId: Number(existingDevice.id), serialNumber };
      }

      // Different owner: record the failure so the wizard can surface a clear
      // error, then reject the request.
      await client.queryObject`
        UPDATE public.device_pairing_tokens
        SET
          failed_at = now(),
          failure_reason = 'device_owned_by_another_user'
        WHERE id = ${pairing.id}
      `;

      await client.queryObject("COMMIT");
      throw new RegisterDeviceError(409, "Device serial number already registered");
    }

    // Happy path: new device.
    const deviceResult = await client.queryObject<{ id: number }>`
      INSERT INTO public.devices ("serialNumber", "plantId", type, user_id)
      VALUES (${serialNumber}, ${pairing.plant_id}, 'humidity', ${pairing.user_id})
      RETURNING id
    `;
    const deviceId = Number(deviceResult.rows[0]?.id);
    if (!deviceId) {
      throw new RegisterDeviceError(500, "Failed to create device");
    }

    await client.queryObject`
      INSERT INTO public.humidity_sensors_config (
        "deviceId",
        "minHumidityThreshold",
        "airValue",
        "waterValue",
        "sleepDurationSeconds"
      )
      VALUES (
        ${deviceId},
        ${DEFAULT_HUMIDITY_CONFIG.minHumidityThreshold},
        ${DEFAULT_HUMIDITY_CONFIG.airValue},
        ${DEFAULT_HUMIDITY_CONFIG.waterValue},
        ${DEFAULT_HUMIDITY_CONFIG.sleepDurationSeconds}
      )
    `;

    await client.queryObject`
      UPDATE public.device_pairing_tokens
      SET
        used_at = now(),
        registered_serial_number = ${serialNumber},
        registered_device_id = ${deviceId}
      WHERE id = ${pairing.id}
    `;

    await client.queryObject("COMMIT");
    return { deviceId, serialNumber };
  } catch (error) {
    // Only roll back if the transaction is still open (i.e. we haven't already
    // committed for the "different owner" failure path above).
    try {
      await client.queryObject("ROLLBACK");
    } catch {
      // Transaction already committed — nothing to roll back.
    }
    throw error;
  }
}

Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
  const databaseUrl = Deno.env.get("SUPABASE_DB_URL");

  if (!anonKey || !databaseUrl) {
    return jsonResponse({ error: "Missing environment variables" }, 500);
  }

  const apiKey = req.headers.get("apikey");
  if (apiKey !== anonKey) {
    return jsonResponse({ error: "Unauthorized" }, 401);
  }

  let body: RegisterDeviceRequest;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ error: "Invalid JSON body" }, 400);
  }

  const token = body.token?.trim();
  const serialNumber = body.serialNumber?.trim();
  if (!token || !serialNumber) {
    return jsonResponse({ error: "token and serialNumber are required" }, 400);
  }

  const pool = new Pool(databaseUrl, 3, true);

  try {
    const connection = await pool.connect();
    try {
      const result = await registerDevice(connection, token, serialNumber);
      return jsonResponse(result);
    } catch (error) {
      if (error instanceof RegisterDeviceError) {
        return jsonResponse({ error: error.message }, error.status);
      }
      const message = error instanceof Error ? error.message : String(error);
      console.error("register-device error:", message);
      return jsonResponse({ error: message }, 500);
    } finally {
      connection.release();
    }
  } finally {
    await pool.end();
  }
});
