CREATE TABLE IF NOT EXISTS "public"."humidity_sensors_config" (
    "id" bigint NOT NULL,
    "minHumidityThreshold" int8 NOT NULL,
    "airValue" int8 NOT NULL,
    "waterValue" int8 NOT NULL,
    "sleep_duration_seconds" int8 NOT NULL,
    "deviceId" int8 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."humidity_sensors_config" OWNER TO "postgres";

COMMENT ON TABLE "public"."humidity_sensors_config" IS 'Configuration table for humidity sensors';

ALTER TABLE "public"."humidity_sensors_config" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."humidity_sensors_config_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."humidity_sensors_config"
    ADD CONSTRAINT "humidity_sensors_config_pkey" PRIMARY KEY ("id"),
    ADD CONSTRAINT "humidity_sensors_config_device_id_fkey" FOREIGN KEY ("deviceId") REFERENCES "public"."devices"("id") ON UPDATE RESTRICT ON DELETE CASCADE;