CREATE TABLE IF NOT EXISTS "public"."battery_measurements" (
    "id" bigint NOT NULL,
    "deviceId" int8 NOT NULL,
    "batteryPercent" int2 NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."battery_measurements" OWNER TO "postgres";

COMMENT ON TABLE "public"."battery_measurements" IS 'Battery charge level measurements periodically recorded from devices';

ALTER TABLE "public"."battery_measurements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battery_measurements_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battery_measurements"
    ADD CONSTRAINT "battery_measurements_pkey" PRIMARY KEY ("id"),
    ADD CONSTRAINT "battery_measurements_device_id_fkey" FOREIGN KEY ("deviceId") REFERENCES "public"."devices"("id") ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE "public"."battery_measurements" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public can insert battery_measurements" ON "public"."battery_measurements" FOR INSERT TO "anon" WITH CHECK (true);
CREATE POLICY "public can read battery_measurements"  ON "public"."battery_measurements" FOR SELECT TO "anon" USING (true);

GRANT ALL ON TABLE "public"."battery_measurements" TO "anon";
GRANT ALL ON TABLE "public"."battery_measurements" TO "authenticated";
GRANT ALL ON TABLE "public"."battery_measurements" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battery_measurements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battery_measurements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battery_measurements_id_seq" TO "service_role";
