CREATE TABLE IF NOT EXISTS "public"."devices" (
    "id" bigint NOT NULL,
    "serialNumber" text NOT NULL,
    "plantId" int8 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."devices" OWNER TO "postgres";

COMMENT ON TABLE "public"."devices" IS 'Table for storing device information';

ALTER TABLE "public"."devices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."devices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."devices"
    ADD CONSTRAINT "devices_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."devices"
    ADD CONSTRAINT "devices_plant_id_fkey" FOREIGN KEY ("plantId") REFERENCES "public"."plants"("id") ON UPDATE RESTRICT ON DELETE CASCADE;